<b><h3><center>House Price Prediction

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df_home= pd.read_csv('home_data.csv')
df_home.head()

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0     Owner                   0     0        2       BHK  1300.236407   
1    Dealer                   0     0        2       BHK  1275.000000   
2     Owner                   0     0        2       BHK   933.159722   
3     Owner                   0     1        2       BHK   929.921143   
4    Dealer                   1     0        2       BHK   999.009247   

   READY_TO_MOVE  RESALE                      ADDRESS  LONGITUDE   LATITUDE  \
0              1       1        Ksfc Layout,Bangalore  12.969910  77.597960   
1              1       1    Vishweshwara Nagar,Mysore  12.274538  76.644605   
2              1       1             Jigani,Bangalore  12.778033  77.632191   
3              1       1  Sector-1 Vaishali,Ghaziabad  28.642300  77.344500   
4              0       1             New Town,Kolkata  22.592200  88.484911   

   TARGET(PRICE_IN_LACS)  
0                   55.0  
1                   51.0  
2                   43.0  
3                   62.5  
4                   60.5

In [4]:
df_home.describe()

UNDER_CONSTRUCTION          RERA       BHK_NO.     SQUARE_FT  \
count        29451.000000  29451.000000  29451.000000  2.945100e+04   
mean             0.179756      0.317918      2.392279  1.980217e+04   
std              0.383991      0.465675      0.879091  1.901335e+06   
min              0.000000      0.000000      1.000000  3.000000e+00   
25%              0.000000      0.000000      2.000000  9.000211e+02   
50%              0.000000      0.000000      2.000000  1.175057e+03   
75%              0.000000      1.000000      3.000000  1.550688e+03   
max              1.000000      1.000000     20.000000  2.545455e+08   

       READY_TO_MOVE        RESALE     LONGITUDE      LATITUDE  \
count   29451.000000  29451.000000  29451.000000  29451.000000   
mean        0.820244      0.929578     21.300255     76.837695   
std         0.383991      0.255861      6.205306     10.557747   
min         0.000000      0.000000    -37.713008   -121.761248   
25%         1.000000      1.000000     18.452663     73.798100   
50%         1.000000      1.000000     20.750000     77.324137   
75%         1.000000      1.000000     26.900926     77.828740   
max         1.000000      1.000000     59.912884    152.962676   

       TARGET(PRICE_IN_LACS)  
count           29451.000000  
mean              142.898746  
std               656.880713  
min                 0.250000  
25%                38.000000  
50%                62.000000  
75%               100.000000  
max             30000.000000

In [5]:
col_price = "Price"

In [6]:
df_home.columns = ['POSTED_BY', 'UNDER_CONSTRUCTION', 'AREA', 'BHK_NO.', 'BHK_OR_RK',
       'SQUARE_FT', 'READY_TO_MOVE', 'RESALE', 'ADDRESS', 'LONGITUDE',
       'LATITUDE', 'Price']

In [7]:
df_home.columns = df_home.columns.str.capitalize()

In [17]:
df_home.columns

Index(['Posted_by', 'Under_construction', 'Area', 'Bhk_no.', 'Bhk_or_rk',
       'Square_ft', 'Ready_to_move', 'Resale', 'Address', 'Longitude',
       'Latitude', 'Price'],
      dtype='object')

In [8]:
#Drooping Coluns which are not of use

In [19]:
df_home = df_home.drop(columns=['Posted_by', 'Under_construction', 'Bhk_no.', 'Bhk_or_rk', 'Ready_to_move', 'Address'],axis=0)

In [20]:
df_home

Area    Square_ft  Resale  Longitude   Latitude  Price
0         0  1300.236407       1  12.969910  77.597960   55.0
1         0  1275.000000       1  12.274538  76.644605   51.0
2         0   933.159722       1  12.778033  77.632191   43.0
3         1   929.921143       1  28.642300  77.344500   62.5
4         0   999.009247       1  22.592200  88.484911   60.5
...     ...          ...     ...        ...        ...    ...
29446     0  2500.000000       1  27.140626  78.043277   45.0
29447     0   769.230769       1  39.945409 -86.150721   16.0
29448     0  1022.641509       1  26.928785  75.828002   27.1
29449     0   927.079009       1  12.900150  80.227910   67.0
29450     1   896.774194       1  26.832353  75.841749   27.8

[29451 rows x 6 columns]

In [22]:
#sns.pairplot(df_home,hue='Price')

In [23]:
df_home.describe()

Area     Square_ft        Resale     Longitude      Latitude  \
count  29451.000000  2.945100e+04  29451.000000  29451.000000  29451.000000   
mean       0.317918  1.980217e+04      0.929578     21.300255     76.837695   
std        0.465675  1.901335e+06      0.255861      6.205306     10.557747   
min        0.000000  3.000000e+00      0.000000    -37.713008   -121.761248   
25%        0.000000  9.000211e+02      1.000000     18.452663     73.798100   
50%        0.000000  1.175057e+03      1.000000     20.750000     77.324137   
75%        1.000000  1.550688e+03      1.000000     26.900926     77.828740   
max        1.000000  2.545455e+08      1.000000     59.912884    152.962676   

              Price  
count  29451.000000  
mean     142.898746  
std      656.880713  
min        0.250000  
25%       38.000000  
50%       62.000000  
75%      100.000000  
max    30000.000000

In [44]:
np.isnan(df_home).sum()

Area         0
Square_ft    0
Resale       0
Longitude    0
Latitude     0
Price        0
dtype: int64

In [26]:

from sklearn.tree import DecisionTreeRegressor

In [29]:
print(df_home.columns)
features = ['Area', 'Square_ft', 'Resale', 'Longitude', 'Latitude']

Index(['Area', 'Square_ft', 'Resale', 'Longitude', 'Latitude', 'Price'], dtype='object')


In [30]:
X = df_home[features]

In [46]:
X.head()
X.shape

(29451, 5)

In [47]:
y = df_home.Price
y.shape

(29451,)

<b>Basic Decision Tree Model

In [48]:
de_model = DecisionTreeRegressor(random_state = 1)
de_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [49]:
de_model.predict(X)

array([55. , 51. , 43. , ..., 27.1, 67. , 27.8])

In [50]:
de_model.score(X,de_model.predict(X))

1.0

In [51]:
from sklearn.metrics import mean_absolute_error

In [56]:
mean_absolute_error(y, de_model.predict(X))
#This is in Sample Score

0.38019187828345413

<b>Out-Sample Score

In [57]:
from sklearn.model_selection import train_test_split

In [61]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)

In [62]:
model = DecisionTreeRegressor()

In [63]:
model.fit(train_X, train_y)

DecisionTreeRegressor()

In [64]:
model.predict(val_X)

array([150. , 710. ,  72. , ...,  39.8,  18.7,  51. ])

In [68]:
mean_absolute_error(val_y,model.predict(val_X)) #This is the Actual error after using Sampling and Training Technique

42.49531354757485

<b>Lessen Over-UnderFitting by Max_leaves_count

In [69]:
#Create a function for training
def get_leaf(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model_leaf = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=1)
    model_leaf.fit(train_X,train_y)
    predicted_val = model_leaf.predict(val_X)
    mea = mean_absolute_error(val_y,predicted_val)
    return mea
    

In [71]:
#Compare with different Tree Leaf Size
comprehend_leaves = [5,25,50,100,250,500,1000,5000,1000]

for i in comprehend_leaves:
    mean_abs = get_leaf(i, train_X, val_X, train_y, val_y)
    print("Max Leaf Nodes : %d \t \t Mean Absolute Error: %d" %(i,mean_abs))

Max Leaf Nodes : 5 	 	 Mean Absolute Error: 74
Max Leaf Nodes : 25 	 	 Mean Absolute Error: 55
Max Leaf Nodes : 50 	 	 Mean Absolute Error: 52
Max Leaf Nodes : 100 	 	 Mean Absolute Error: 51
Max Leaf Nodes : 250 	 	 Mean Absolute Error: 47
Max Leaf Nodes : 500 	 	 Mean Absolute Error: 44
Max Leaf Nodes : 1000 	 	 Mean Absolute Error: 43
Max Leaf Nodes : 5000 	 	 Mean Absolute Error: 43
Max Leaf Nodes : 1000 	 	 Mean Absolute Error: 43


In [72]:
#Getting the best at 1000 Max Leaf Size
#Now Fit the Model
final_model = DecisionTreeRegressor(max_leaf_nodes=1000,random_state=1)
final_model.fit(X,y)
final_model.predict(X)

array([77.09649123, 64.05986842, 40.4       , ..., 38.35741776,
       52.60719794, 36.1825    ])

In [73]:
df_home['Predicted_DT'] = final_model.predict(X)

In [75]:
df_home.head()

Area    Square_ft  Resale  Longitude   Latitude  Price  Predicted_DT
0     0  1300.236407       1  12.969910  77.597960   55.0     77.096491
1     0  1275.000000       1  12.274538  76.644605   51.0     64.059868
2     0   933.159722       1  12.778033  77.632191   43.0     40.400000
3     1   929.921143       1  28.642300  77.344500   62.5     39.121396
4     0   999.009247       1  22.592200  88.484911   60.5     46.181818

In [78]:
final_model.score(X,df_home['Predicted_DT'])

1.0

<center><b>Random Forest

In [80]:
from sklearn.ensemble import RandomForestRegressor

In [81]:
ran_model = RandomForestRegressor(random_state=1)

In [83]:
ran_model.fit(train_X,train_y)

RandomForestRegressor(random_state=1)

In [84]:
ran_model.predict(val_X)

array([138.622    ,  94.2284127,  74.836    , ...,  41.495    ,
        29.285    ,  69.436    ])

In [86]:
mean_absolute_error(val_y,ran_model.predict(val_X))

36.29509201096374