<b><h2>Loan Data Example</h2></b>

<b>Importing the Package</b>

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True, linewidth=120, precision=2)
#These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

<b>Importing the Data</b>

In [3]:
raw_data_np=np.genfromtxt("loan-data.csv", delimiter=';', skip_header=1, autostrip=True) 
#Autostrip-leading nor trailing white spaces.
#Linewidth Width of the display Table
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

<b>Checking for incomplete Data</b>

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
temp_fill=np.nanmax(raw_data_np)+1 #Highest Value in the Whole dataset
temp_mean=np.nanmean(raw_data_np, axis=0) #Axis=0 mean for each column

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: Mean of empty slice
  


In [6]:
#One full empty column full of Nan
temp_mean #Here Nan columns are probably the ones with NOn-Numeric Dataset

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,      440.92,
               nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temp_stats=np.array([np.nanmin(raw_data_np, axis=0), temp_mean, np.nanmax(raw_data_np, axis=0)])
#Including the mean, min max

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: All-NaN slice encountered
  """Entry point for launching an IPython kernel.


In [8]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,       31.42,
                nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,      440.92,
                nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,     1372.97,
                nan,         nan,         nan,         nan,         nan,    41913.62]])

<b>Splitting the DataSet</b>


In [9]:
column_strings=np.argwhere(np.isnan(temp_mean)).squeeze() #Columns where cells have value as Nan will be strings
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [10]:
column_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

<b>Re-Importing the Dataset</b>

In [11]:
loan_data_strings=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=column_strings,
                                dtype=np.str)

loan_data_strings #The String Dataset

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [12]:
loan_data_numeric=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=column_numeric,
                                filling_values=temp_fill)

loan_data_numeric #The Numeric Dataset

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

<b>The Names of the Columns</b>

In [13]:
header_full=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                skip_footer=raw_data_np.shape[0], #Will skip 10000 values from bottom and show only column Head
                                autostrip=True,
                                dtype=np.str)

header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [14]:
header_strings, header_numeric = header_full[column_strings], header_full[column_numeric]

In [15]:
header_numeric
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

<b>Creating Checkpoints</b>

In [16]:
#Want to avoid losing the progress, we save data at points, we create our own checkpoint with Header, Data and File Name

In [17]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data) #Saving with different values of header and dataset
    checkpoint_variable=np.load(file_name+".npz")
    return(checkpoint_variable)

In [18]:
checkpoint_test=checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [19]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [20]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [21]:
 np.array_equal(checkpoint_test['data'], loan_data_strings)
    #True if two arrays have the same shape and element np.array_equal

True

 <b>Manipulating String Column</b>

In [22]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [23]:
header_strings[0]='Issue_date'
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [24]:
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [25]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15',
       'Oct-15', 'Sep-15'], dtype='<U69')

In [26]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15") #Will Strip '-15' of Every Cell

In [27]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [28]:
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i]
                                    ,i
                                    ,loan_data_strings[:,0])
    
    #Converting Month Name into Numbers

In [29]:
np.unique(loan_data_strings[:,0])


array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [30]:
loan_data_strings[:,0].astype(dtype=np.int32)

array([ 5,  0,  9, ...,  6,  4, 12])

<b>Loan Status</b>

In [31]:
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [32]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)',
       'Late (31-120 days)'], dtype='<U69')

In [33]:
#Spilitting into groups with Good and Bad
status_bad =np.array(['','Charged Off','Default','Late (31-120 days)'])

loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [34]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

<b>Term</b>

In [35]:
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [36]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [37]:
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [38]:
#Null value with the worst Case here- 60 months being the worst
header_strings[2]='Term_months'

In [39]:
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=='',
                                60,
                                loan_data_strings[:,2])

In [40]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

<b>Grade and SubGrade</b>

In [41]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [42]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3',
       'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5'],
      dtype='<U69')

In [43]:
#If missing in Subgrade, B-B5, C-C5 rather than allocating with the worst possible case of G5

<b>Filling Subgrade</b>


In [44]:
np.unique(loan_data_strings[:,3])[1:] #Excluding '' and A to H

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [45]:
for i in np.unique(loan_data_strings[:,3])[1:]: 
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='') & (loan_data_strings[:,3]==i)
                                   ,i+'5'
                                   ,loan_data_strings[:,4])

In [46]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3',
       'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5'],
      dtype='<U69')

In [47]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3',
        'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5'],
       dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235,
        162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [48]:
#Now we will create a seperate column for those missing spaces and mark with H1
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]=np.where(loan_data_strings[:,4]==''
                                   ,'H1'
                                   ,loan_data_strings[:,4])

In [49]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3',
       'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H1'],
      dtype='<U69')

<b>Removing Grade</b>

In [50]:
np.unique(loan_data_strings[:,3], return_counts=True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

In [51]:
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [52]:
loan_data_strings=np.delete(loan_data_strings,3,axis=1)

In [53]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [54]:
header_strings[3]

'grade'

In [55]:
header_strings=np.delete(header_strings,3)

In [56]:
header_strings[3]

'sub_grade'

<b>Converting SubGrade</b>

In [57]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3',
       'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H1'],
      dtype='<U69')

In [58]:
#Creating a dictionary with Values 1-36
keys=list(np.unique(loan_data_strings[:,3]))
values=list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))

dict_sub_grade=dict(zip(keys,values)) #Since its a tuple thus ()

In [59]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [60]:
#Converting A1-1, A2-2
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where((loan_data_strings[:,3]==i),
                                   dict_sub_grade[i],
                                   loan_data_strings[:,3])

In [61]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26',
       '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6', '7', '8', '9'], dtype='<U69')

<b>Verification Status feature</b>

In [62]:
header_strings

array(['Issue_date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [63]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [64]:
#Consider '' as not Verified, Good as bad
loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='') | (loan_data_strings[:,4]=='Not Verified'),0,1)

In [65]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

<b>URL</b>

In [66]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [67]:
np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [68]:
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [69]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [70]:
#Since the leftovers are equivalent to the ids in the Header full 

In [71]:
np.array_equal(loan_data_numeric[:,0],loan_data_strings[:,5])

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py:2327: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())


False

In [72]:
loan_data_numeric[:,0].astype(dtype=np.int32)
loan_data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [73]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),
              loan_data_strings[:,5].astype(dtype=np.int32))

True

In [74]:
#Getting rid of url
loan_data_strings=np.delete(loan_data_strings,5,axis=1)

In [75]:
header_strings=np.delete(header_strings,5)

In [76]:
header_strings

array(['Issue_date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

<b>Address State</b>

In [77]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA',
       'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR',
       'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [78]:
header_strings[5]='State Address'

In [79]:
np.unique(loan_data_strings[:,5]).size

50

In [80]:
#We will assume '' as the IOWA(IA)
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA',
        'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR',
        'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,   84,   84,  116,
         210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,  341,   57,  130,  777,  312,   83,
         108,  320,   40,  107,   24,  143,  758,   74,  242,   17,  216,  148,   49,   27], dtype=int64))

In [81]:
states_names,states_count =np.unique(loan_data_strings[:,5],return_counts=True)

In [82]:
states_count_sorted=np.argsort(-states_count)

In [83]:
states_count

array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,   84,   84,  116,
        210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,  341,   57,  130,  777,  312,   83,
        108,  320,   40,  107,   24,  143,  758,   74,  242,   17,  216,  148,   49,   27], dtype=int64)

In [84]:
states_count_sorted #Confusion here done- 5=1336 at 5th index position

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7, 41, 32,  2, 17, 36,
       39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28, 40, 45, 27, 20], dtype=int64)

In [85]:
states_count[states_count_sorted],states_names[states_count_sorted]

(array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,
         160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,   74,   74,   61,   58,
          57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64),
 array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO',
        'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM',
        'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'))

In [86]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [87]:
loan_data_strings[:,5]=np.where((loan_data_strings[:,5]==''),0,loan_data_strings[:,5])

In [88]:
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_west),1,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_south),2,loan_data_strings[:,5])

In [89]:
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_east),4,loan_data_strings[:,5])

In [90]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

<b>Converting to Numbers</b>

In [91]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [92]:
loan_data_strings=loan_data_strings.astype(dtype=np.int)

In [93]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [94]:
header_strings

array(['Issue_date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'State Address'], dtype='<U19')

<b>Checkpoint1 Strings</b>

In [95]:
Checkpoint_Strings=checkpoint('checkpoint-strings',header_strings,loan_data_strings)

In [96]:
Checkpoint_Strings['header']

array(['Issue_date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'State Address'], dtype='<U19')

In [97]:
Checkpoint_Strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

<b>Manipulating Numeric Data</b>

In [98]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [99]:
np.isnan(loan_data_numeric).sum()

0

<b>Substitute Fillers</b>

In [100]:
#Earlier we substituted with 0, Now we need to do it with Worst possible values
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

<b>ID</b>

In [101]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [102]:
temp_fill

68616520.0

In [103]:
np.isin(loan_data_numeric[:,0],temp_fill)

array([False, False, False, ..., False, False, False])

In [104]:
np.isin(loan_data_numeric[:,0],temp_fill).sum() #No true, no MIssing Values

0

In [105]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

<B>Temp_Stats</B>

In [106]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,       31.42,
                nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,      440.92,
                nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,     1372.97,
                nan,         nan,         nan,         nan,         nan,    41913.62]])

In [107]:
temp_stats[:,column_numeric]
#Top Min, Middle Mean, Max Last

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

<b>Funded Amount</b>

In [108]:
loan_data_numeric[:,2]=np.where((loan_data_numeric[:,2]==temp_fill),
                               temp_stats[0,column_numeric[2]],
                               loan_data_numeric[:,2])
loan_data_numeric[:2]

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ]])

<b>Loan Amount, Interest Rate, Total Payment, Installment</b>

In [109]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [110]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i]= np.where((loan_data_numeric[:,i]==temp_fill),
                                    temp_stats[2,column_numeric[i]],
                                    loan_data_numeric[:,i])


In [111]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [112]:
#We have found more clear values by removing temp_fill and adding temp_stats[min,mean,max]

<b><h3>Currency Exchange</h3></b>

#We are in the European Office, thus we require to convert USD into EURO
We will introduce a new column -exchange_rates

In [113]:
EUS_USD=np.genfromtxt('EUR-USD.csv', delimiter=',', autostrip=True, skip_header=1, usecols=[3])

In [114]:
EUS_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [115]:
np.unique(loan_data_strings[:,0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [116]:
exchange_rate=loan_data_strings[:,0]

In [117]:
for i in range(1,13):
    exchange_rate= np.where((exchange_rate==i),
                          EUS_USD[i-1],
                          exchange_rate)
    
exchange_rate= np.where((exchange_rate==0),
                      np.mean(EUS_USD),
                      exchange_rate)

In [118]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [119]:
exchange_rate.shape

(10000,)

In [120]:
loan_data_numeric.shape

(10000, 6)

In [121]:
#Scalar Exchange rate to 2-d
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [122]:
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))

In [123]:
loan_data_numeric


array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [124]:
header_numeric=np.append(header_numeric,'Exchange_rate')

In [125]:
header_numeric #or np.concatenate((header_numeric,np.array(['Excchange_rate'])))

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate'], dtype='<U19')

<b>From USD to EUR</b>

In [126]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate'], dtype='<U19')

In [127]:
column_dollar=np.array([1,2,4,5])
column_dollar

array([1, 2, 4, 5])

In [128]:
loan_data_numeric[:,[column_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [129]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape((loan_data_numeric[:,i] / loan_data_numeric[:,6]),(10000,1))))
    
    #Using Np.shape for dimension change

In [130]:
loan_data_numeric #The values have been appended into new Columns

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

<b>Changing the Header also</b>


In [131]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate'], dtype='<U19')

In [132]:
header_dollar_name=np.array([i+'_EUS' for i in header_numeric[column_dollar]])

In [133]:
header_dollar_name

array(['loan_amnt_EUS', 'funded_amnt_EUS', 'installment_EUS', 'total_pymnt_EUS'], dtype='<U15')

In [134]:
header_numeric=np.append(header_numeric,header_dollar_name)

In [135]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_rate', 'loan_amnt_EUS',
       'funded_amnt_EUS', 'installment_EUS', 'total_pymnt_EUS'], dtype='<U19')

In [136]:
#Changing the name of existing Columns of USD
header_numeric[column_dollar]=np.array([i+'_USD' for i in header_numeric[column_dollar]])

In [137]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'Exchange_rate',
       'loan_amnt_EUS', 'funded_amnt_EUS', 'installment_EUS', 'total_pymnt_EUS'], dtype='<U19')

In [138]:
#Now Sorting according to our need
column_index_order=[0,1,7,2,8,3,4,9,5,10,6]
header_numeric=header_numeric[column_index_order]

In [139]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUS', 'funded_amnt_USD', 'funded_amnt_EUS', 'int_rate', 'installment_USD',
       'installment_EUS', 'total_pymnt_USD', 'total_pymnt_EUS', 'Exchange_rate'], dtype='<U19')

In [140]:
#Since loan_data_numeric is 2-D
loan_data_numeric=loan_data_numeric[:,column_index_order]

<b>Interest Rates</b>

In [141]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUS', 'funded_amnt_USD', 'funded_amnt_EUS', 'int_rate', 'installment_USD',
       'installment_EUS', 'total_pymnt_USD', 'total_pymnt_EUS', 'Exchange_rate'], dtype='<U19')

In [143]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [145]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [146]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

<b>Checkpoint2</b>

In [148]:
checkpoint_numeric=checkpoint('Numerical_values',header_numeric,loan_data_numeric)

In [152]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUS', 'funded_amnt_USD', 'funded_amnt_EUS', 'int_rate', 'installment_USD',
        'installment_EUS', 'total_pymnt_USD', 'total_pymnt_EUS', 'Exchange_rate'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

<b>Completing the Dataset</b>

In [154]:
#Now we are going to combine the dataset
#So far- We Split up thearray into Two
#Cleaned and Preprocessed each part

<b>Creating the Complete Dataset</b>

In [155]:
loan_data_numeric.shape #or checkpoint_numeric['data'].shape

(10000, 11)

In [157]:
Checkpoint_Strings['data'].shape #or loan_data_strings.shape

(10000, 6)

In [160]:
loan_data = np.hstack((checkpoint_numeric['data'],loan_data_strings))

In [162]:
np.isnan(loan_data).sum()

0

In [165]:
loan_header = np.concatenate((checkpoint_numeric['header'],Checkpoint_Strings['header']))

<b>Sorting the New Dataset

In [170]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [167]:
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [168]:
np.argsort(loan_data[:,0]) #Argsort gives the indices of the array not the array elements

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [169]:
loan_data[np.argsort(loan_data[:,0])] #This sorts the whole data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [171]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [173]:
np.argsort(loan_data[:,0]) #Checking the indices after sorting

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

<b>Storting the new Dataset

In [175]:
loan_dataset = np.vstack((loan_header,loan_data))

In [176]:
np.savetxt("Loan-Dataset-Preprocessed-by-Numpy_27.csv", loan_dataset, fmt="%s", delimiter=',')