<h3><b>Panda Series</b></h3>

In [1]:
import pandas as pd

In [64]:
data=pd.read_csv('Sample-Scalar.csv',squeeze=True) # Squeeze converts to Series
location_data=data.copy() #Copying data variable 1 to 2
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 14
4    Location 20
Name: Locations, dtype: object

In [65]:
type(location_data)


pandas.core.series.Series

In [68]:
location_data.describe()

count              5
unique             5
top       Location 3
freq               1
Name: Locations, dtype: object

In [69]:
len(location_data)

5

In [70]:
location_data.nunique()

5

In [71]:
location_data.drop_duplicates()

0     Location 3
1     Location 6
2     Location 8
3    Location 14
4    Location 20
Name: Locations, dtype: object

In [75]:
Unique_val=location_data.unique() #Coverting Unique data to array
print(Unique_val)

['Location 3' 'Location 6' 'Location 8' 'Location 14' 'Location 20']


In [77]:
type(location_data.unique())

numpy.ndarray

 <b>Convert Series: .values .array .to_numpy</b>

In [78]:
import pandas as pd
import numpy as np

In [79]:
prices_per_cat=pd.Series({'Product A':22500, 'Product B':34000, 'Product C':45000})
prices_per_cat

Product A    22500
Product B    34000
Product C    45000
dtype: int64

In [82]:
prices_per_cat.keys()

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [83]:
prices_per_cat.values# Not to use .values

array([22500, 34000, 45000], dtype=int64)

In [84]:
type(prices_per_cat)

pandas.core.series.Series

In [87]:
prices_per_cat.array

<PandasArray>
[22500, 34000, 45000]
Length: 3, dtype: int64

In [88]:
type(prices_per_cat.array)

pandas.core.arrays.numpy_.PandasArray

In [90]:
prices_per_cat.to_numpy()

array([22500, 34000, 45000], dtype=int64)

In [92]:
type(prices_per_cat.to_numpy()) #Use this one   

numpy.ndarray

<b>Panda Series :.sort_values()</b>

In [93]:
import pandas as pd

In [94]:
numbers=pd.Series([15,22,67,23,88])
numbers

0    15
1    22
2    67
3    23
4    88
dtype: int64

In [96]:
numbers.sort_values()

0    15
1    22
3    23
2    67
4    88
dtype: int64

In [97]:
numbers.sort_values(ascending=False)

4    88
2    67
3    23
1    22
0    15
dtype: int64

In [99]:
numbers.sort_index()

0    15
1    22
2    67
3    23
4    88
dtype: int64

In [100]:
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 14
4    Location 20
Name: Locations, dtype: object

In [105]:
location_data.sort_values(ascending=False)
#Values are sorted alphabetically

2     Location 8
1     Location 6
0     Location 3
4    Location 20
3    Location 14
Name: Locations, dtype: object

<b>Attribute and Method Chaining</b>

In [103]:
 location_data.index

RangeIndex(start=0, stop=5, step=1)

In [104]:
location_data.name

'Locations'

In [110]:
location_data.index.name="Index"

In [111]:
location_data

Index
0     Location 3
1     Location 6
2     Location 8
3    Location 14
4    Location 20
Name: Locations, dtype: object

In [112]:
location_data.sort_values().head(3) #Method Chaining- type.head.head....

Index
3    Location 14
4    Location 20
0     Location 3
Name: Locations, dtype: object

In [113]:
location_data.index.to_numpy()

array([0, 1, 2, 3, 4], dtype=int64)

In [116]:
location_data.index.to_numpy()

array([0, 1, 2, 3, 4], dtype=int64)

<b>.sort_index()</b>

In [117]:
location_data_sv=location_data.sort_values(ascending=False)
location_data_sv.head()

Index
2     Location 8
1     Location 6
0     Location 3
4    Location 20
3    Location 14
Name: Locations, dtype: object

In [118]:
location_data_sv.index

Int64Index([2, 1, 0, 4, 3], dtype='int64', name='Index')

In [119]:
location_data_sv.sort_index()

Index
0     Location 3
1     Location 6
2     Location 8
3    Location 14
4    Location 20
Name: Locations, dtype: object