In [1]:
import numpy as np

In [2]:
array_a=np.array([[1,2,3],[4,3,6]])

In [3]:
array_a

array([[1, 2, 3],
       [4, 3, 6]])

<b>Specific Values</b>

In [4]:
array_a[0]

array([1, 2, 3])

In [5]:
array_a[0][1]

2

In [6]:
array_a[1][0]

4

In [7]:
array_a[0,1]

2

In [8]:
array_a[:,0]

array([1, 4])

<b>Negative Indices</b>

In [9]:
array_b=np.array([1,2,3])

In [10]:
array_b[-1]

3

<b>Assigning Values in Numpy

In [11]:
array_a[0,2]=9
array_a

array([[1, 2, 9],
       [4, 3, 6]])

In [12]:
array_a[0]=5

In [13]:
array_a

array([[5, 5, 5],
       [4, 3, 6]])

In [14]:
list_a=[7,8,4]

In [15]:
array_a[0]=list_a

In [16]:
array_a

array([[7, 8, 4],
       [4, 3, 6]])

In [17]:
type(array_a[0])

numpy.ndarray

In [18]:
array_a[:]=9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [19]:
array_a=9

In [20]:
array_a

9

<b>ElementWise Properties

In [21]:
array_c=np.array([7,8,9])
array_d=np.array([[1,2,3],[6,7,8]])

In [22]:
array_c+2

array([ 9, 10, 11])

In [23]:
array_c+array_d

array([[ 8, 10, 12],
       [13, 15, 17]])

In [24]:
array_c

array([7, 8, 9])

In [25]:
array_c+array_d[0]

array([ 8, 10, 12])

<b>Type of Data supported by Numpy

In [29]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_a=np.array([[1,2,3],[4,5,6]],dtype="float32")
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [32]:
array_a=np.array([[1,2,3],[4,5,6]],dtype=np.float32)

In [33]:
array_a=np.array([[1,2,3],[4,5,6]],dtype=np.complex64)

In [35]:
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [36]:
array_a=np.array([[1,2,3],[4,5,6]],dtype=np.bool)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [38]:
array_a=np.array([[1,2,3],[4,5,6]],dtype=np.str)
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

<b>Fundamentals of Numpy Functions</b>

In [40]:
array_a=np.array([1,2,7])
array_b=np.array([[1],[2]])
matrix_c=np.array([[1,2,3],[4,5,6]])

In [42]:
np.add(array_a,matrix_c)#We will Broadcast

array([[ 2,  4, 10],
       [ 5,  7, 13]])

In [43]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

<b>Type Casting

In [44]:
np.add(array_a,matrix_c,dtype=np.float64)

array([[ 2.,  4., 10.],
       [ 5.,  7., 13.]])

<b>Running over an Axis

In [45]:
np.mean(matrix_c,axis=0)

array([2.5, 3.5, 4.5])

In [46]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.mean(matrix_c,axis=1)

array([2., 5.])

<h3><b>Datatypes</b></h3>

In [48]:
import numpy as np

<b>NdArrays</b>

In [49]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [50]:
type(array_a)

numpy.ndarray

In [51]:
array_a.shape

(3,)

In [52]:
array_b=np.array([[7,8,9],[10,11,12]])
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [56]:
array_b.shape

(2, 3)

In [57]:
array_c=np.array(3)
array_c

array(3)

In [58]:
array_c.shape

()

In [59]:
type(array_c)

numpy.ndarray

<b>Array vs Lists

In [60]:
list_a=[1,2,3,4,5,6]
list_a

[1, 2, 3, 4, 5, 6]

In [61]:
len(list_a)

6

In [71]:
array_a=([[1,2,3],[4,5,6]])

In [73]:
array_a

[[1, 2, 3], [4, 5, 6]]

In [72]:
type(array_a)

list

In [76]:
len(array_a)

2

In [77]:
len(array_a[0])

3

In [75]:
#Convert list into Array
arr=np.array(array_a)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
import math

In [81]:
arr[1,0]

4

In [82]:
array_e=math.sqrt(arr[1,0])
array_e

2.0

In [83]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

<b>String vs Object Number</b>

In [84]:
lead_co_lt=np.genfromtxt("Sample-Val.csv", delimiter=',')
lead_co_lt

array([[      nan,       nan,       nan,       nan,       nan],
       [      nan,       nan,       nan, 5.000e+03, 2.500e+01],
       [      nan,       nan,       nan, 7.000e+00, 1.500e+01],
       [      nan,       nan,       nan, 3.000e+04, 3.300e+01],
       [      nan,       nan,       nan, 2.500e+03, 1.000e+01],
       [      nan,       nan,       nan, 1.000e+00, 1.500e+01],
       [      nan,       nan,       nan, 1.000e+04, 1.700e+01],
       [      nan,       nan,       nan, 1.000e+02, 1.900e+01],
       [      nan,       nan,       nan, 7.390e+02, 2.400e+01],
       [      nan,       nan,       nan, 1.000e+03, 1.200e+01],
       [      nan,       nan,       nan, 1.000e+03, 1.300e+01],
       [      nan,       nan,       nan, 5.000e+03, 1.400e+01],
       [      nan,       nan,       nan, 4.653e+03, 1.800e+01]])

In [85]:
lead_co_lt=np.genfromtxt("Sample-Val.csv", delimiter=',',dtype=np.int32)
lead_co_lt

array([[   -1,    -1,    -1,    -1,    -1],
       [   -1,    -1,    -1,  5000,    25],
       [   -1,    -1,    -1,     7,    15],
       [   -1,    -1,    -1, 30000,    33],
       [   -1,    -1,    -1,  2500,    10],
       [   -1,    -1,    -1,     1,    15],
       [   -1,    -1,    -1, 10000,    17],
       [   -1,    -1,    -1,   100,    19],
       [   -1,    -1,    -1,   739,    24],
       [   -1,    -1,    -1,  1000,    12],
       [   -1,    -1,    -1,  1000,    13],
       [   -1,    -1,    -1,  5000,    14],
       [   -1,    -1,    -1,  4653,    18]])

In [86]:
lead_co_lt=np.genfromtxt("Sample-Val.csv", delimiter=',',dtype=np.str)

In [87]:
lead_co_lt

array([['Date', ' Description', ' Account', ' Amount', 'Maturity'],
       ['24-09-2013', 'Initial deposit for goal creation from SBA-9978',
        'savings for me and Bro', '5000', '25'],
       ['30-09-2013', 'Interest Deposit', 'savings for me and Bro', '7',
        '15'],
       ['10/10/2013', 'Miscellaneous Deposit', 'savings for me and Bro',
        '30000', '33'],
       ['10/10/2013', 'Miscellaneous Deposit', 'savings for me and Bro',
        '2500', '10'],
       ['15-10-2013', 'Miscellaneous Deposit', 'savings for me and Bro',
        '1', '15'],
       ['30-11-2013', 'User added funds from SBA-9978',
        'savings for me and Bro', '10000', '17'],
       ['5/12/2013', 'User added funds from SBA-9978',
        'savings for me and Bro', '100', '19'],
       ['31-12-2013', 'Interest Deposit', 'savings for me and Bro',
        '739', '24'],
       ['1/1/2014', 'User added funds from SBA-9978',
        'savings for me and Bro', '1000', '12'],
       ['5/1/2014', 'User added fu