<B>Clean and Preprocess Data using Numpy

In [1]:
#How to discover missing values and fill them up
#Ways to remove irrelevant data
#Sort shuffle strip reshape stacka

In [2]:
import numpy as np

In [3]:
lead_co_file=np.loadtxt('Test_Creation.csv', delimiter=',')

In [4]:
lead_co_file

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [37]:
np.isnan(lead_co_file)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ...,
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [6]:
np.isnan(lead_co_file).sum() #It gives the count 

0

In [7]:
#fILE With missing params NAN
lead_co_file=np.genfromtxt('Test_Creation1.csv', delimiter=',')

In [8]:
np.isnan(lead_co_file).sum()

16

In [9]:
#Filling every NAN with zero
lead_co_file=np.genfromtxt('Test_Creation1.csv', delimiter=',',filling_values=0)


In [10]:
np.isnan(lead_co_file).sum()

0

In [11]:
#Filling with the maximum values
temp_fill=np.nanmax(lead_co_file).round(2)+1

In [12]:
temp_fill

70.0

In [13]:
lead_co_file=np.genfromtxt('Test_Creation1.csv', delimiter=',',filling_values=temp_fill)

In [14]:
lead_co_file

array([[ 2.        , 21.        , 70.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

<b>Substituting missing values

In [15]:
temp_mean=np.nanmean(lead_co_file,axis=0).round(2)

In [16]:
temp_mean[0]
temp_mean

array([ 1.11, 15.24, 54.2 ,  9.12,  4.12])

In [17]:
lead_co_file[:,0] #Column with index zero, Hence all rows but 1 column

array([ 2.,  0.,  1.,  1.,  2.,  1.,  1.,  0.,  1.,  1.,  1.,  2.,  1.,
        1.,  0.,  0.,  1.,  0.,  2.,  1.,  0.,  1.,  0.,  0.,  2.,  1.,
        0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  1.,  1.,
        0.,  1.,  0.,  4.,  1.,  2.,  2.,  2.,  0.,  0.,  1.,  0.,  0.,
        1.,  2.,  0.,  1.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.,  1.,
        2.,  0.,  0.,  0.,  0.,  3.,  2.,  0.,  2.,  0.,  2.,  0.,  0.,
        1.,  1.,  2.,  0.,  0.,  2.,  0.,  0.,  2.,  1.,  1.,  0.,  0.,
        0.,  1.,  2.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  1.,  0.,  1.,  1.,  5.,  0.,  1.,  0.,  2.,  0.,  2.,
        1.,  4.,  1.,  3.,  0.,  3.,  1.,  2.,  0.,  1.,  3.,  0.,  2.,
        2.,  0.,  2.,  2.,  3.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,
        2.,  1.,  1.,  0.,  1.,  3.,  1.,  2.,  2.,  1.,  3.,  2.,  2.,
        0.,  0.,  1.,  0.,  1.,  0.,  1.,  2.,  1.,  0.,  2.,  3.,  1.,
        2.,  1.,  4.,  2.,  2.,  1.,  3.,  1.,  2.,  2.,  0.,  1

In [18]:
np.mean(lead_co_file[:,0]).round(2)

1.11

In [19]:
lead_co_file[:,0]=np.where(lead_co_file[:,0]==temp_fill, temp_mean[0],lead_co_file[:,0]) #Like ternary Operator (if:cond1:cond2)

In [20]:
np.mean(lead_co_file[:,0]).round(2)

0.97

In [21]:
for i in range(lead_co_file.shape[1]):
    lead_co_file[:,i]=np.where(lead_co_file[:,i]==temp_fill, temp_mean[i],lead_co_file[:,i])

In [22]:
for i in range(lead_co_file.shape[1]):
    lead_co_file[:,i]=np.where(lead_co_file[:,i]<0, temp_mean[i],lead_co_file[:,i])

<b>Reshaping

In [23]:
#numpy.reshape(array, shape, order = 'C')

In [24]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')

In [25]:
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [26]:
lead_dataset.shape

(1000, 5)

In [27]:
np.reshape(lead_dataset,(5,1000))

array([[ 2.        , 21.        , 47.        , ..., 52.        ,
         7.26848267,  6.        ],
       [ 1.        , 18.        , 51.        , ..., 59.        ,
         3.13933438,  2.        ],
       [ 1.        , 17.        , 51.        , ..., 51.        ,
         4.43157288,  4.        ],
       [ 0.        , 13.        , 50.        , ..., 43.        ,
        10.76406889,  1.        ],
       [ 2.        , 12.        , 59.        , ..., 47.        ,
         8.19234137,  6.        ]])

In [28]:
lead_dataset.transpose()

array([[ 2.        ,  0.        ,  1.        , ...,  1.        ,
         1.        ,  2.        ],
       [21.        , 21.        , 13.        , ..., 15.        ,
        15.        , 20.        ],
       [47.        , 62.        , 50.        , ..., 54.        ,
        57.        , 47.        ],
       [20.05945799, 10.58624666, 12.25758194, ...,  9.17892527,
        14.39721513,  8.19234137],
       [ 2.        ,  6.        ,  2.        , ...,  1.        ,
         4.        ,  6.        ]])

In [29]:
np.reshape(lead_dataset,(2,5,500))

array([[[ 2.        , 21.        , 47.        , ..., 59.        ,
          5.18309581,  6.        ],
        [ 0.        , 14.        , 50.        , ..., 52.        ,
          7.26848267,  6.        ],
        [ 1.        , 18.        , 51.        , ..., 58.        ,
         18.42475925,  6.        ],
        [ 1.        , 10.        , 55.        , ..., 59.        ,
          3.13933438,  2.        ],
        [ 1.        , 17.        , 51.        , ..., 50.        ,
         12.98184693,  1.        ]],

       [[ 0.        , 13.        , 48.        , ..., 51.        ,
          4.43157288,  4.        ],
        [ 0.        , 13.        , 50.        , ..., 60.        ,
          1.30464095,  6.        ],
        [ 0.        , 12.        , 59.        , ..., 43.        ,
         10.76406889,  1.        ],
        [ 2.        , 12.        , 59.        , ..., 51.        ,
          9.75111127,  1.        ],
        [ 0.        , 15.        , 49.        , ..., 47.        ,
          8.19

In [30]:
lead_dataset=np.reshape(lead_dataset,(100,10,5))

In [31]:
lead_dataset

array([[[  2.        ,  21.        ,  47.        ,  20.05945799,
           2.        ],
        [  0.        ,  21.        ,  62.        ,  10.58624666,
           6.        ],
        [  1.        ,  13.        ,  50.        ,  12.25758194,
           2.        ],
        ...,
        [  0.        ,  17.        ,  58.        ,   4.92609105,
           5.        ],
        [  1.        ,  12.        ,  57.        , -15.82393876,
           5.        ],
        [  1.        ,  16.        ,  56.        ,   8.61139411,
           1.        ]],

       [[  1.        ,  14.        ,  60.        ,   9.04272751,
           6.        ],
        [  2.        ,  18.        ,  45.        ,   2.69144317,
           6.        ],
        [  1.        ,  16.        ,  63.        ,  15.96309797,
           4.        ],
        ...,
        [  0.        ,  12.        ,  54.        ,  12.44462352,
           5.        ],
        [  2.        ,  11.        ,  52.        ,   8.33834179,
           5.    

<b>Removing values from ND Arrays

In [32]:
#numpy.delete(array, object, axis = None)

In [41]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset.shape

(1000, 5)

In [49]:
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [47]:
np.delete(lead_dataset, 1).shape #Delets and shows in Scalar Array

(4999,)

In [48]:
lead_dataset.size

5000

In [50]:
 np.delete(lead_dataset,0,axis=0) #Deleted 1st Row

array([[ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       [ 1.        , 17.        , 53.        ,  7.8137595 ,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [52]:
np.delete(lead_dataset,0,axis=1) #Deleted 1st Column

array([[21.        , 47.        , 20.05945799,  2.        ],
       [21.        , 62.        , 10.58624666,  6.        ],
       [13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [15.        , 54.        ,  9.17892527,  1.        ],
       [15.        , 57.        , 14.39721513,  4.        ],
       [20.        , 47.        ,  8.19234137,  6.        ]])

In [55]:
np.delete(lead_dataset, [2,4,6], axis=0) #Deleted row 2,4,6

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 17.        , 53.        ,  7.8137595 ,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [56]:
np.delete(np.delete(lead_dataset, (2,4,6), axis=0), [0,2], axis=1) #Double delete

array([[21.        , 20.05945799,  2.        ],
       [21.        , 10.58624666,  6.        ],
       [17.        ,  7.8137595 ,  2.        ],
       ...,
       [15.        ,  9.17892527,  1.        ],
       [15.        , 14.39721513,  4.        ],
       [20.        ,  8.19234137,  6.        ]])

In [35]:
lead_delete.shape

(1000, 4)

<b>Sorting Arrays</b>

In [57]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset.shape

(1000, 5)

In [58]:
np.sort(lead_dataset) #Default rows in ascending order axis=-1

array([[ 2.        ,  2.        , 20.05945799, 21.        , 47.        ],
       [ 0.        ,  6.        , 10.58624666, 21.        , 62.        ],
       [ 1.        ,  2.        , 12.25758194, 13.        , 50.        ],
       ...,
       [ 1.        ,  1.        ,  9.17892527, 15.        , 54.        ],
       [ 1.        ,  4.        , 14.39721513, 15.        , 57.        ],
       [ 2.        ,  6.        ,  8.19234137, 20.        , 47.        ]])

In [62]:
np.sort(lead_dataset, axis=0) #Columns arranged also horizontally across columns (axis 1).

array([[  0.        ,   4.        ,  38.        , -19.68716184,
          1.        ],
       [  0.        ,   4.        ,  39.        , -15.82393876,
          1.        ],
       [  0.        ,   5.        ,  40.        , -13.53845836,
          1.        ],
       ...,
       [  5.        ,  27.        ,  66.        ,  28.119642  ,
          6.        ],
       [  5.        ,  27.        ,  67.        ,  29.22529875,
          6.        ],
       [  5.        ,  30.        ,  69.        ,  30.90897045,
          6.        ]])

In [66]:
np.sort(lead_dataset, axis=None) #1-D Array

array([-19.68716184, -15.82393876, -13.53845836, ...,  66.        ,
        67.        ,  69.        ])

In [63]:
np.set_printoptions(suppress=True) #Removing the Scientifc Notations

In [68]:
#Decreasing
-np.sort(-lead_dataset) # The minus '-' sign changes to Decreasing

array([[47.        , 21.        , 20.05945799,  2.        ,  2.        ],
       [62.        , 21.        , 10.58624666,  6.        ,  0.        ],
       [50.        , 13.        , 12.25758194,  2.        ,  1.        ],
       ...,
       [54.        , 15.        ,  9.17892527,  1.        ,  1.        ],
       [57.        , 15.        , 14.39721513,  4.        ,  1.        ],
       [47.        , 20.        ,  8.19234137,  6.        ,  2.        ]])

In [76]:
np.sort(lead_dataset[:,1])

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04496207, 0.14746898, 0.54875454, 0.57910036, 0.67474388,
       0.73724663, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [74]:
lead_dataset.sort(axis=0)

<b><h2>Argument Functions</h2></b>

<b>ArgumentSort np.argsort</b>

In [81]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [83]:
np.argsort(lead_dataset) #This is giving index after sorting

array([[0, 4, 3, 1, 2],
       [0, 4, 3, 1, 2],
       [0, 4, 3, 1, 2],
       ...,
       [0, 4, 3, 1, 2],
       [0, 4, 3, 1, 2],
       [0, 4, 3, 1, 2]], dtype=int64)

In [80]:
np.sort(lead_dataset)

array([[ 2.        ,  2.        , 20.05945799, 21.        , 47.        ],
       [ 0.        ,  6.        , 10.58624666, 21.        , 62.        ],
       [ 1.        ,  2.        , 12.25758194, 13.        , 50.        ],
       ...,
       [ 1.        ,  1.        ,  9.17892527, 15.        , 54.        ],
       [ 1.        ,  4.        , 14.39721513, 15.        , 57.        ],
       [ 2.        ,  6.        ,  8.19234137, 20.        , 47.        ]])

In [84]:
np.argsort(lead_dataset, axis=0) #Index after sorting in Vertically 

array([[499, 319, 939, 440, 499],
       [435, 897, 261,   8, 524],
       [879, 923, 708, 844, 165],
       ...,
       [110, 597, 412,   5, 605],
       [433, 976, 346, 155, 628],
       [509, 917, 606, 549, 999]], dtype=int64)

In [86]:
#Verification we get it
lead_dataset[499,4]

1.0

In [87]:
#We can get it more simpler
np.argsort(lead_dataset[:,2]) #Sorting in one column only

array([939, 261, 708, 962, 157, 954, 913, 344, 609, 554, 815, 351, 629,
       866, 656, 463, 387, 799, 698, 584, 271, 494, 101, 430, 335, 289,
       305, 245, 142, 323, 610, 459, 326, 571, 895, 714, 958,  11, 870,
       771, 776, 864, 255, 947,  59, 316, 227, 207, 340, 349, 827, 818,
       177, 728, 107, 720, 608, 134, 253, 961, 196, 980, 209, 155, 145,
       985, 239, 689, 936, 639, 877, 338, 791, 476, 732, 556, 568, 579,
       697, 248,   0, 999,  57, 514, 937, 331, 333, 153, 722, 543, 228,
       225, 535, 533, 695, 746, 905, 348, 516, 181, 809, 817, 500, 171,
       878,  14,  13, 524, 945, 398, 567, 616, 296, 409, 594, 593, 314,
       647, 427, 653, 650, 481, 570, 439,  56, 613, 855, 696, 247, 814,
       179, 710, 587, 805, 503, 790, 318, 667, 768, 583,  32, 342, 672,
       740, 279, 337, 744, 265, 758, 694, 763,  39, 767, 745, 283, 604,
       431,  88, 474,  83, 900, 150, 384, 977, 951, 393, 148, 499, 912,
       104, 217, 267, 470, 127, 471, 901, 671, 582, 754, 677, 46

In [89]:
lead_dataset.argsort(axis=0)

array([[499, 319, 939, 440, 499],
       [435, 897, 261,   8, 524],
       [879, 923, 708, 844, 165],
       ...,
       [110, 597, 412,   5, 605],
       [433, 976, 346, 155, 628],
       [509, 917, 606, 549, 999]], dtype=int64)

In [ ]:
#It does not overwrite the original array only for testing

<b>np.argwhere()</b>

In [ ]:
#To check element we need, helping in getting coordinates [i,j]

In [90]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [91]:
np.argwhere(lead_dataset) #Checks individual element satisfy condition | (i,j) Location given here
#The default condition is to check values different from zero

array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [999,   2],
       [999,   3],
       [999,   4]], dtype=int64)

In [92]:
np.argwhere(lead_dataset==False) #Checking only for zeros Important

array([[  1,   0],
       [  7,   0],
       [ 14,   0],
       [ 15,   0],
       [ 17,   0],
       [ 20,   0],
       [ 22,   0],
       [ 23,   0],
       [ 26,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 39,   0],
       [ 41,   0],
       [ 47,   0],
       [ 48,   0],
       [ 50,   0],
       [ 51,   0],
       [ 54,   0],
       [ 56,   0],
       [ 57,   0],
       [ 58,   0],
       [ 59,   0],
       [ 62,   0],
       [ 63,   0],
       [ 66,   0],
       [ 67,   0],
       [ 68,   0],
       [ 69,   0],
       [ 72,   0],
       [ 74,   0],
       [ 76,   0],
       [ 77,   0],
       [ 81,   0],
       [ 82,   0],
       [ 84,   0],
       [ 85,   0],
       [ 89,   0],
       [ 90,   0],
       [ 91,   0],
       [ 95,   0],
       [ 96,   0],
       [ 98,   0],
       [ 99,   0],
       [100,   0],
       [101,   0],
       [102,   0],
       [103,   0],
       [105,   0],
       [107,   0],
       [111,

In [93]:
lead_dataset[31,0]

0.0

In [94]:
np.argwhere(lead_dataset %2==0) #Check for even

array([[  0,   0],
       [  0,   4],
       [  1,   0],
       ...,
       [999,   0],
       [999,   1],
       [999,   4]], dtype=int64)

In [95]:
lead_dataset.argwhere() #Not applicable

AttributeError: 'numpy.ndarray' object has no attribute 'argwhere'

In [98]:
#Compare with isNan and argwhere
lead_dataset_Nan=np.genfromtxt('Test_Creation1.csv', delimiter=',')

In [112]:
np.isnan(lead_dataset_Nan)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ...,
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [113]:
np.argwhere(np.isnan(lead_dataset_Nan)) #Checking for values where are Nan

array([[  0,   2],
       [ 14,   1],
       [ 16,   3],
       [ 89,   3],
       [143,   3],
       [302,   1],
       [396,   1],
       [424,   4],
       [468,   4],
       [493,   0],
       [497,   3],
       [556,   2],
       [616,   1],
       [705,   3],
       [707,   0],
       [776,   3]], dtype=int64)

In [114]:
#Removing all the values of Nan
for array_index in np.argwhere(np.isnan(lead_dataset_Nan)):
    lead_dataset_Nan[array_index[0], array_index[0]] = 0

IndexError: index 14 is out of bounds for axis 1 with size 5

In [115]:
lead_dataset_Nan[14,1]

nan

In [108]:
np.isnan(lead_dataset_Nan).sum()

16

<B>Shuffling</B>

In [ ]:

#Rearranging the parts of dataset

In [117]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')[:8]
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       [ 1.        , 17.        , 53.        ,  7.8137595 ,  2.        ],
       [ 2.        ,  9.        , 51.        ,  9.18823262,  5.        ],
       [ 1.        , 19.        , 65.        , 28.119642  ,  5.        ],
       [ 1.        , 12.        , 53.        ,  7.92970684,  1.        ],
       [ 0.        , 17.        , 58.        ,  4.92609105,  5.        ]])

In [123]:
np.random.shuffle(lead_dataset) #Shuffled but in proper columns

In [124]:
lead_dataset

array([[ 1.        , 19.        , 65.        , 28.119642  ,  5.        ],
       [ 1.        , 17.        , 53.        ,  7.8137595 ,  2.        ],
       [ 1.        , 12.        , 53.        ,  7.92970684,  1.        ],
       [ 2.        ,  9.        , 51.        ,  9.18823262,  5.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 17.        , 58.        ,  4.92609105,  5.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ]])

In [125]:
lead_dataset_shuffle=np.loadtxt("Test_Creation.csv",delimiter=',')

In [126]:
from numpy.random import shuffle # whenevr using function more than once, try to import

In [130]:
shuffle(lead_dataset_shuffle)
lead_dataset_shuffle

array([[ 2.        , 19.        , 57.        , 15.59769097,  4.        ],
       [ 0.        , 16.        , 49.        ,  7.0114726 ,  1.        ],
       [ 2.        , 16.        , 64.        ,  5.59270379,  2.        ],
       ...,
       [ 1.        , 14.        , 46.        , -1.07800288,  2.        ],
       [ 0.        , 16.        , 62.        ,  4.61305948,  1.        ],
       [ 1.        , 11.        , 54.        , 13.3314535 ,  4.        ]])

In [134]:
#Random Generators - Generate Data and Shuffle Data
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [162]:
array_rg=gen(pcg(seed= 362))
array_rg.shuffle(lead_dataset_shuffle) #Array_RG is generator variable
lead_dataset_shuffle

array([[ 1.        , 11.        , 61.        , 14.65256522,  4.        ],
       [ 1.        , 16.        , 55.        , -1.83167415,  6.        ],
       [ 0.        , 11.        , 53.        , 11.67879361,  6.        ],
       ...,
       [ 1.        , 14.        , 55.        , 12.25938184,  5.        ],
       [ 2.        , 24.        , 58.        ,  7.89270271,  5.        ],
       [ 1.        , 14.        , 63.        ,  7.45603258,  1.        ]])

<b>Casting</b>

In [167]:
lead_dataset=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [164]:
#Creating a new array with Converted Data Type Like-Decimals to Int

In [166]:
lead_dataset.astype(dtype= np.int32)

array([[ 2, 21, 47, 20,  2],
       [ 0, 21, 62, 10,  6],
       [ 1, 13, 50, 12,  2],
       ...,
       [ 1, 15, 54,  9,  1],
       [ 1, 15, 57, 14,  4],
       [ 2, 20, 47,  8,  6]])

In [169]:
lead_dataset_caststr=lead_dataset.astype(dtype= np.str)

In [170]:
lead_dataset_caststr

array([['2.0', '21.0', '47.0', '20.059457987167505', '2.0'],
       ['0.0', '21.0', '62.0', '10.586246657566498', '6.0'],
       ['1.0', '13.0', '50.0', '12.257581935890457', '2.0'],
       ...,
       ['1.0', '15.0', '54.0', '9.178925268915227', '1.0'],
       ['1.0', '15.0', '57.0', '14.397215125442711', '4.0'],
       ['2.0', '20.0', '47.0', '8.192341369607929', '6.0']], dtype='<U32')

In [171]:
type(lead_dataset_caststr)

numpy.ndarray

In [173]:
lead_dataset_caststr.astype(dtype= np.int32) #We cant directly cast STR to INT

ValueError: invalid literal for int() with base 10: '2.0'

In [176]:
#Converting into Strings
lead_dataset_castfloat= lead_dataset_caststr.astype(dtype= np.float32)
lead_dataset_castfloat.astype(dtype= np.int32)
#Issue with the decimal placing

array([[ 2, 21, 47, 20,  2],
       [ 0, 21, 62, 10,  6],
       [ 1, 13, 50, 12,  2],
       ...,
       [ 1, 15, 54,  9,  1],
       [ 1, 15, 57, 14,  4],
       [ 2, 20, 47,  8,  6]])

In [178]:
lead_dataset_castint=lead_dataset_caststr.astype(dtype=np.float32).astype(dtype= np.int32) #Combine Transformation
#Python runs code, left to right

In [179]:
lead_dataset_castint

array([[ 2, 21, 47, 20,  2],
       [ 0, 21, 62, 10,  6],
       [ 1, 13, 50, 12,  2],
       ...,
       [ 1, 15, 54,  9,  1],
       [ 1, 15, 57, 14,  4],
       [ 2, 20, 47,  8,  6]])

<b>Stripping</b><br><i>np.chararray.strip</i><br>Transform Text into int by Stripping

In [235]:
#Only for Non-Numeric Columns Removing specific parts of strings
lead_dataset_strip=np.genfromtxt('Test_Creationstr.csv', delimiter=',', dtype= np.str, skip_header=1, usecols=[1,2,5])

In [236]:
lead_dataset_strip

array([['21', '62', '4.0.3 and up'],
       ['13', '50', '4.0.3 and up'],
       ['17', '53', '4.2 and up'],
       ...,
       ['15', '54', '4.0 and up'],
       ['15', '57', '2.3.3 and up'],
       ['20', '47', '']], dtype='<U18')

In [237]:
np.chararray.strip(lead_dataset_strip[:,2], " and") #Here 2 in the index of col fetched

chararray(['4.0.3 and up', '4.0.3 and up', '4.2 and up', '4.4 and up',
           '2.3 and up', '4.0.3 and up', '4.2 and up', '3.0 and up',
           '4.0.3 and up', '4.1 and up', '4.0 and up', '4.1 and up',
           '4.4 and up', '2.3 and up', '4.2 and up', '4.1 and up',
           '2.3 and up', '4.0.3 and up', '4.1 and up', '4.1 and up',
           '4.0.3 and up', '4.0.3 and up', '4.1 and up', '4.1 and up',
           '3.0 and up', '4.0.3 and up', '4.0.3 and up', '2.3 and up',
           '2.3 and up', '4.0.3 and up', '2.3 and up', '4.0 and up',
           '4.1 and up', '4.1 and up', '4.1 and up', '4.4 and up',
           '2.3.3 and up', '4.0.3 and up', '4.0 and up', '4.0.3 and up',
           '4.0.3 and up', 'Varies with device', '4.1 and up',
           '4.1 and up', '4.1 and up', '4.1 and up', '4.1 and up',
           '2.3 and up', '4.0.3 and up', '4.1 and up', '4.1 and up',
           'Varies with device', '4.1 and up', '4.1 and up', '4.0 and up',
           '4.4 and up', '4.1 

In [238]:
lead_dataset_strip[:,2]=np.chararray.strip(lead_dataset_strip[:,2], " and up")

In [239]:
lead_dataset_strip

array([['21', '62', '4.0.3'],
       ['13', '50', '4.0.3'],
       ['17', '53', '4.2'],
       ...,
       ['15', '54', '4.0'],
       ['15', '57', '2.3.3'],
       ['20', '47', '']], dtype='<U18')

In [240]:
#Using Np.where() Transformation 
lead_dataset_strip[:,2] = np.where(lead_dataset_strip[:,2] == '4.0.3', '_', lead_dataset_strip[:,2])

In [241]:
lead_dataset_strip

array([['21', '62', '_'],
       ['13', '50', '_'],
       ['17', '53', '4.2'],
       ...,
       ['15', '54', '4.0'],
       ['15', '57', '2.3.3'],
       ['20', '47', '']], dtype='<U18')

<b>Stacking Data</b><br><i>np.stack np.vstack np.hstack np.dstack</i>

In [244]:
lead_data_stack=np.loadtxt("Test_Creation.csv", delimiter=',')
lead_data_stack

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [246]:
#Recall
lead_data_stack_Nan=np.genfromtxt("Test_Creation1.csv",delimiter=',')

temp_fill=np.nanmax(lead_data_stack_Nan).round(2)+1
temp_mean=np.nanmean(lead_data_stack_Nan, axis=0).round(2)

lead_data_stack_Nan=np.genfromtxt("Test_Creation1.csv", delimiter=',', filling_values=temp_fill)

for i in range(lead_data_stack_Nan.shape[1]):
    lead_data_stack_Nan[:,i] = np.where(lead_data_stack_Nan[:,i]==temp_fill, temp_mean[i], lead_data_stack_Nan[:,i])

In [251]:
np.isnan(lead_data_stack_Nan).sum()

0

In [252]:
#We can stack array of matching shapes to create a larger array
#D- Depth Stack

In [257]:
 np.stack((lead_data_stack[:,1],lead_data_stack[:,0])) #Using it as a tuple hence 2()

array([[21., 21., 13., ..., 15., 15., 20.],
       [ 2.,  0.,  1., ...,  1.,  1.,  2.]])

In [256]:
np.transpose(lead_data_stack[:,:2]) #Similar to stack

array([[ 2.,  0.,  1., ...,  1.,  1.,  2.],
       [21., 21., 13., ..., 15., 15., 20.]])

In [258]:
 np.stack((lead_data_stack[:,1],lead_data_stack[:,0]), axis=1) #From Row to Column

array([[21.,  2.],
       [21.,  0.],
       [13.,  1.],
       ...,
       [15.,  1.],
       [15.,  1.],
       [20.,  2.]])

In [268]:
lead_data_stack_Nan.shape

(1000, 5)

In [273]:
np.vstack((lead_data_stack, lead_data_stack_Nan)).shape #Vertical Append

(2000, 5)

In [283]:
np.vstack((lead_data_stack[:,1], lead_data_stack_Nan[:,1]))

array([[21., 21., 13., ..., 15., 15., 20.],
       [21., 21., 13., ..., 15., 15., 20.]])

In [281]:
np.hstack((lead_data_stack,lead_data_stack_Nan)).shape #Horizontal Append

(1000, 10)

In [284]:
np.dstack((lead_data_stack,lead_data_stack_Nan))

array([[[ 2.        ,  2.        ],
        [21.        , 21.        ],
        [47.        , 54.17      ],
        [20.05945799, 20.05945799],
        [ 2.        ,  2.        ]],

       [[ 0.        ,  0.        ],
        [21.        , 21.        ],
        [62.        , 62.        ],
        [10.58624666, 10.58624666],
        [ 6.        ,  6.        ]],

       [[ 1.        ,  1.        ],
        [13.        , 13.        ],
        [50.        , 50.        ],
        [12.25758194, 12.25758194],
        [ 2.        ,  2.        ]],

       ...,

       [[ 1.        ,  1.        ],
        [15.        , 15.        ],
        [54.        , 54.        ],
        [ 9.17892527,  9.17892527],
        [ 1.        ,  1.        ]],

       [[ 1.        ,  1.        ],
        [15.        , 15.        ],
        [57.        , 57.        ],
        [14.39721513, 14.39721513],
        [ 4.        ,  4.        ]],

       [[ 2.        ,  2.        ],
        [20.        , 20.        ],
     

In [287]:
np.dstack((lead_data_stack,lead_data_stack_Nan)).shape #(Row,Col,Depth)

(1000, 5, 2)

In [288]:
np.dstack((lead_data_stack,lead_data_stack_Nan))[0] #This is first row of both Sheets

array([[ 2.        ,  2.        ],
       [21.        , 21.        ],
       [47.        , 54.17      ],
       [20.05945799, 20.05945799],
       [ 2.        ,  2.        ]])

In [289]:
np.dstack((lead_data_stack,lead_data_stack_Nan))[0,:,0]

array([ 2.        , 21.        , 47.        , 20.05945799,  2.        ])

In [290]:
np.stack((lead_data_stack,lead_data_stack_Nan), axis=-1) #Equals to dStack

array([[[ 2.        ,  2.        ],
        [21.        , 21.        ],
        [47.        , 54.17      ],
        [20.05945799, 20.05945799],
        [ 2.        ,  2.        ]],

       [[ 0.        ,  0.        ],
        [21.        , 21.        ],
        [62.        , 62.        ],
        [10.58624666, 10.58624666],
        [ 6.        ,  6.        ]],

       [[ 1.        ,  1.        ],
        [13.        , 13.        ],
        [50.        , 50.        ],
        [12.25758194, 12.25758194],
        [ 2.        ,  2.        ]],

       ...,

       [[ 1.        ,  1.        ],
        [15.        , 15.        ],
        [54.        , 54.        ],
        [ 9.17892527,  9.17892527],
        [ 1.        ,  1.        ]],

       [[ 1.        ,  1.        ],
        [15.        , 15.        ],
        [57.        , 57.        ],
        [14.39721513, 14.39721513],
        [ 4.        ,  4.        ]],

       [[ 2.        ,  2.        ],
        [20.        , 20.        ],
     

<b>Concatenate</b><br>Linking together objects in a chain in a <i>existing axis</i>

In [292]:
lead_data_concat=np.loadtxt("Test_Creation.csv", delimiter=',')
lead_data_concat

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [295]:
#Concate 1st two rows
np.concatenate((lead_data_concat[0,:],lead_data_concat[1,:]))

array([ 2.        , 21.        , 47.        , 20.05945799,  2.        ,
        0.        , 21.        , 62.        , 10.58624666,  6.        ])

In [297]:
#For 2D Array
#Recall Nan
lead_data_concat_Nan= np.genfromtxt("Test_Creation1.csv",delimiter=',')

temp_fill=np.nanmax(lead_data_concat_Nan).round(2)+1
temp_mean=np.nanmean(lead_data_concat_Nan, axis=0).round(2)

lead_data_concat_Nan=np.genfromtxt("Test_Creation1.csv", delimiter=',', filling_values=temp_fill)

for i in range (lead_data_concat_Nan.shape[1]):
    lead_data_concat_Nan[:,i]=np.where(lead_data_concat_Nan[:,i]== temp_fill,temp_mean[i], lead_data_concat_Nan[:,i])

lead_data_concat_Nan

array([[ 2.        , 21.        , 54.17      , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [298]:
np.concatenate((lead_data_concat,lead_data_concat_Nan))

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [300]:
np.concatenate((lead_data_concat,lead_data_concat_Nan)).shape

(2000, 5)

In [301]:
np.concatenate((lead_data_concat,lead_data_concat_Nan), axis=1)

array([[ 2.        , 21.        , 47.        , ..., 54.17      ,
        20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , ..., 62.        ,
        10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , ..., 50.        ,
        12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        , ..., 54.        ,
         9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , ..., 57.        ,
        14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        , ..., 47.        ,
         8.19234137,  6.        ]])

In [302]:
np.concatenate((lead_data_concat,lead_data_concat_Nan),axis=1).shape

(1000, 10)

In [307]:
array_1=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
array_2=array_1*2

In [311]:
np.concatenate((array_1,array_2))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [313]:
np.concatenate((array_1,array_2), axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [314]:
#Np.concatenate works exactly like hstack(axis=0), vstack(axis=1), dstack(axis=2) 

<b>Unique Values</b>

In [316]:
lead_dataset_unique=np.loadtxt("Test_Creation.csv",delimiter=',')
lead_dataset_unique

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])

In [317]:
np.unique(lead_dataset_unique)

array([-19.68716184, -15.82393876, -13.53845836, ...,  66.        ,
        67.        ,  69.        ])

In [318]:
np.unique(lead_dataset_unique[:,0])

array([0., 1., 2., 3., 4., 5.])

In [322]:
#How many times each one appers
np.transpose(np.unique(lead_dataset_unique[:,0], return_counts=True))

array([[  0., 383.],
       [  1., 355.],
       [  2., 194.],
       [  3.,  49.],
       [  4.,  16.],
       [  5.,   3.]])

In [323]:
np.unique(lead_dataset_unique[:,0], return_counts=True, return_index=True)
#Middle array is Index telling where did they appear for the first time

(array([0., 1., 2., 3., 4., 5.]),
 array([  1,   2,   0,  36,  28, 110], dtype=int64),
 array([383, 355, 194,  49,  16,   3], dtype=int64))