<b>Learning Numpy Basics</b>

In [1]:
import numpy as np

In [2]:
#Scalars
s=5
s

5

In [3]:
#Vectors
v= np.array([5,-2,4])
v

array([ 5, -2,  4])

In [4]:
#Matrix
m= np.array([[5,12,6],[4,-2,3]])
m


array([[ 5, 12,  6],
       [ 4, -2,  3]])

In [24]:
#Type of array
type(s)
type(v)
type(m)

numpy.ndarray

In [6]:
#Data SHapes
m.shape

(2, 3)

In [7]:
v.shape

(3,)

In [8]:
#Tensors are 3D Arrays
m1=np.array([[2,3,5],[2,6,3]])
m2=np.array([[6,3,-3],[0,4,1]])

In [9]:
t=np.array([m1,m2])
t

array([[[ 2,  3,  5],
        [ 2,  6,  3]],

       [[ 6,  3, -3],
        [ 0,  4,  1]]])

In [10]:
t.shape

(2, 2, 3)

In [11]:
#Addition/Sub/Mul/Div
add=m1+m2
add

array([[ 8,  6,  2],
       [ 2, 10,  4]])

In [12]:
m1+2

array([[4, 5, 7],
       [4, 8, 5]])

In [13]:
sub=m1-m2
sub

array([[-4,  0,  8],
       [ 2,  2,  2]])

In [14]:
mul=m1*m2
mul

array([[ 12,   9, -15],
       [  0,  24,   3]])

In [15]:
div=m2/m1
div

array([[ 3.        ,  1.        , -0.6       ],
       [ 0.        ,  0.66666667,  0.33333333]])

In [16]:
#Transposing Vectors and Matrices
A=np.array([[2,3,4],[6,7,3]])
A

array([[2, 3, 4],
       [6, 7, 3]])

In [17]:
A.T

array([[2, 6],
       [3, 7],
       [4, 3]])

In [18]:
#dOT Product of Scalars and Vectors
X=np.dot(m1,m2.T)
X

array([[ 6, 17],
       [21, 27]])

In [19]:
Y=np.dot(m,v)
Y

array([25, 36])

In [20]:
#Numpy Array
array_a=np.array([1,2,3])
array_a
array_b=np.array([[2,4,6],[5,22,4]])
array_b

array([[ 2,  4,  6],
       [ 5, 22,  4]])