<B>Working with arrays-Slicing

In [1]:
import numpy as np

In [2]:
mat_A=np.array([[1,2,4],[5,4,6]])
mat_A

array([[1, 2, 4],
       [5, 4, 6]])

In [3]:
array2D = np.arange(12).reshape(4,3)
array2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
array3D = np.arange(18).reshape(3,2,3)
array3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

<b>Basic Slicing</b>

<b>Basic Slicing on 1-D Array [Start:Stop:Step]</b>

In [5]:
array_a=np.arange(20) # SHortcut making array of 0-19
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
array_a[2:15:1]#Start:Stop:Step

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
array_a[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<b>Basic slicing on 2-D Array [row start: row stop, Column Start : Column Stop]</b>

In [8]:
mat_A[:]#entire Ndarray [row start: row stop, Column Start : Column Stop]

array([[1, 2, 4],
       [5, 4, 6]])

In [9]:
mat_A[:,:]#Slicing -Interval Indexing & produces 2-D slice(with w brackets)

array([[1, 2, 4],
       [5, 4, 6]])

In [10]:
mat_A[0:0]#Python of SLice from row with INdex 0 and ending befoe the same row

array([], shape=(0, 3), dtype=int32)

In [11]:
mat_A[0:1]#Row with index 0 and row with INdex 1

array([[1, 2, 4]])

In [12]:
mat_A[0:2]

array([[1, 2, 4],
       [5, 4, 6]])

In [13]:
mat_A[:1]

array([[1, 2, 4]])

In [14]:
mat_A[:2]

array([[1, 2, 4],
       [5, 4, 6]])

In [15]:
mat_A[1:]

array([[5, 4, 6]])

In [16]:
mat_A[2:]

array([], shape=(0, 3), dtype=int32)

In [17]:
mat_A[:-1]#Ok

array([[1, 2, 4]])

In [18]:
mat_A[:,1]

array([2, 4])

In [19]:
#Now using Rows along with COlumn slicing

In [20]:
mat_A[:,1:]#:-Rows, 1:-Columns

array([[2, 4],
       [4, 6]])

In [21]:
mat_A[1:,1:]

array([[4, 6]])

In [22]:
mat_A[1,:]#First Row i=1, Print all 

array([5, 4, 6])

In [23]:
mat_A[:,2]

array([4, 6])

<b>Conditional Slicing</b>

In [24]:
mat_C=np.arange(12).reshape(3,4)
mat_C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
mat_C[:,0]

array([0, 4, 8])

In [26]:
mat_C[:,0]>2 #Conditions it give 0>2, !4>2, !8>2

array([False,  True,  True])

In [27]:
mat_C[:,:]>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
mat_C[mat_C[:,:]>2] #2D into 1D , cannot create array on certain conditions

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
mat_C[mat_C[:,:]%2==0] #2D into 1D , cannot create array on certain conditions

array([ 0,  2,  4,  6,  8, 10])

In [30]:
#Using And and OR
mat_C[(mat_C[:,:]%2==0) & (mat_C[:,:]<=4)] 
mat_C[(mat_C[:,:]%2==0) | (mat_C[:,:]<=4)] 

array([ 0,  1,  2,  3,  4,  6,  8, 10])

<b>Squeeze Functions and Array dimensionality

In [31]:
mat_D=np.array([[1,2,4],[5,6,8],[2,7,3]])
mat_D

array([[1, 2, 4],
       [5, 6, 8],
       [2, 7, 3]])

In [32]:
type(mat_D[0,0])#Scalar value

numpy.int32

In [33]:
print(mat_D[0,0])

1


In [34]:
print(mat_D[0,0:1])

[1]


In [35]:
print(mat_D[0:1,0:1])

[[1]]


In [36]:
print(mat_D[0,0].shape) #Scalar
type(mat_D[0,0:1].shape) #Vector
print(mat_D[0:1,0:1].shape) #Matrix

()
(1, 1)


In [37]:
mat_D[0:1,0:1].squeeze()

array(1)

In [38]:
print(mat_D[0:1,0:1].squeeze())

1


In [39]:
#variable_name.squeeze()=np.squeeze(variable_name) & Squeeze converts into scalar

In [40]:
print(mat_D[0,0].squeeze().shape) #Scalar
print(mat_D[0,0:1].squeeze().shape) #Vector
print(mat_D[0:1,0:1].squeeze().shape) #Matrix

()
()
()


<b>Generating data w/ Numpy</b>

In [41]:
import numpy as np

<b>np.empty(),np.zero(),np.ones(),np.full()

In [42]:
arr_empty=np.empty(shape=(2,3))

In [43]:
arr_empty

array([[2.12199579e-314, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 2.12199579e-314]])

In [44]:
arr_zero=np.zeros(shape=(2,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr_ones=np.ones(shape=(2,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
arr_full=np.full(shape=(2,3), fill_value=2)
arr_full

array([[2, 2, 2],
       [2, 2, 2]])

<b>"_like Functions</b>

In [47]:
matrix_A=np.array([[1,2,4,6],[7,2,3,5],[4,5,6,2]])
matrix_A

array([[1, 2, 4, 6],
       [7, 2, 3, 5],
       [4, 5, 6, 2]])

In [48]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like

array([[         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248]])

In [49]:
array_zeros_like=np.zeros_like(matrix_A)
array_zeros_like

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
array_ones_like=np.ones_like(matrix_A)
array_ones_like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

<b>np.arange</b>

In [51]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
np.arange(12,30)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [53]:
np.arange(start=15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
np.arange(start=15,stop=30)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

<b>Random Generators in Numpy

In [55]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [56]:
array_rg=gen(pcg())

In [57]:
array_rg.normal()

0.9920332068956556

In [58]:
array_rg.normal(size=(3,4))

array([[-1.04710958,  1.4097561 , -0.72034977,  0.31996875],
       [ 0.02880368,  1.05098112, -0.88200074, -0.88170626],
       [ 0.040365  ,  0.46953078,  0.35552886, -1.60726187]])

In [59]:
array_rg=gen(pcg(seed=365))
array_rg.normal(size=(3,4))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641],
       [-0.6866818 , -0.50922173, -0.7999526 ,  0.73041825],
       [ 0.08825439, -2.1177576 ,  0.65526774, -0.48095012]])

In [60]:
array_rg=gen(pcg(seed=364))

In [61]:
array_rg.integers(10,size=(2,3))

array([[5, 0, 1],
       [6, 8, 0]], dtype=int64)

In [62]:
array_rg.random(size=(2,3))

array([[0.17905446, 0.15484995, 0.69665394],
       [0.42768091, 0.22399782, 0.56151082]])

In [63]:
array_rg.choice([1,2,4,5,6], size=(4,4))

array([[5, 5, 4, 1],
       [2, 6, 4, 5],
       [4, 5, 4, 4],
       [5, 1, 2, 2]])

In [67]:
array_rg=gen(pcg(seed=365))
array_rg.choice([1,2,4,5,6],p=[0.2,0.1,0.2,0.2,0.3], size=(4,4))

array([[6, 6, 5, 2],
       [5, 1, 6, 1],
       [6, 4, 6, 4],
       [1, 5, 4, 2]])

<b>Probability Distributions in Numpy

In [78]:
array_col1=gen(pcg(seed=365))

In [84]:
array_col1.poisson(size=(3,2))

array([[2, 2],
       [1, 1],
       [1, 0]], dtype=int64)

In [80]:
array_col2=gen(pcg(seed=365))
array_col2.poisson(lam=15,size=(5,5))

array([[18, 16, 17, 18, 20],
       [19,  8, 13, 15, 16],
       [17, 11, 13, 16, 12],
       [15, 20, 13, 20, 11],
       [13, 13, 21, 18, 13]], dtype=int64)

In [81]:
array_col3=gen(pcg(seed=365))
array_col3.binomial(n=90,p=0.6,size=(5,5))

array([[52, 51, 47, 58, 49],
       [53, 56, 52, 53, 59],
       [63, 59, 48, 65, 53],
       [52, 48, 60, 46, 49],
       [49, 49, 54, 51, 47]], dtype=int64)

In [82]:
array_col4=gen(pcg(seed=365))
array_col4.logistic(loc=9,scale=3.2,size=(5,5))

array([[12.67380859, 12.79871633, 10.69078312,  4.63075804, 11.19431431],
       [ 0.49928334, 11.91611281,  2.24774751, 15.36640683,  8.92394448],
       [13.95585862,  8.44216846,  0.89887734, 11.65495148,  7.25437647],
       [ 6.25614726,  8.99507839,  8.82747183, 10.66754853,  9.63602316],
       [10.96611425, -0.84248588, 12.0326274 , 14.44994085,  3.96209736]])

<b><h3>Applications of Random Data-Test Creation

In [85]:
array_col=gen(pcg(seed=365))
array_col1=array_col.poisson(size=(1000))
array_col2=array_col.poisson(lam=15,size=(1000))
array_col3=array_col.binomial(n=90,p=0.6,size=(1000))
array_col4=array_col.logistic(loc=9,scale=3.2,size=(1000))
array_col5=array_col.choice([1,2,4,5,6],p=[0.2,0.1,0.2,0.2,0.3], size=(1000))

In [93]:
ran_test_data=np.array([array_col1,array_col2,array_col3,array_col4,array_col5])
test_creation=ran_test_data.transpose()

In [88]:
ran_test_data.shape

(5, 1000)

<b>Saving to csv

In [95]:
np.savetxt("Test_Creation.csv",test_creation,fmt="%s",delimiter=',')

<b>Importing from csv

In [96]:
np.genfromtxt("Test_Creation.csv",delimiter=',')

array([[ 2.        , 21.        , 47.        , 20.05945799,  2.        ],
       [ 0.        , 21.        , 62.        , 10.58624666,  6.        ],
       [ 1.        , 13.        , 50.        , 12.25758194,  2.        ],
       ...,
       [ 1.        , 15.        , 54.        ,  9.17892527,  1.        ],
       [ 1.        , 15.        , 57.        , 14.39721513,  4.        ],
       [ 2.        , 20.        , 47.        ,  8.19234137,  6.        ]])